keys:
  - &users:
    - &ltlr 93822605C442D674624431B92F394641FD9E298A
  - &hosts:
    - &sparrow 0007CB38069B986F3739E4F8D0A796E4149F6E87
    - &bee 0553987A6C422E4462632494ED1F0C6720F4207D
    - &tower E13A6C611BC60D19CC0B68B3F6DFCCC6153E906C
    - &h0 47E21190D5A43CBE17303EEABA59C47ACC4E10A9
    - &moni 731ACDDDB283606B43D0E73AB6D3F1FCDD6DA21B

creation_rules:
  - path_regex: hosts/moni/secrets.yaml
    key_groups:
      - pgp: [ *moni, *ltlr ]
  - path_regex: hosts/h0/secrets.yaml
    key_groups:
      - pgp: [ *h0, *ltlr ]
  - path_regex: users/leo.secrets.yaml
    key_groups:
      - pgp: [ *tower, *ltlr ]
  - path_regex: hosts/tower/secrets.yaml
    key_groups:
      - pgp: [ *tower, *ltlr ]
  - path_regex: hosts/sparrow/secrets.yaml
    key_groups:
      - pgp: [ *sparrow, *ltlr ]
  - path_regex: hosts/bee/secrets.yaml
    key_groups:
      - pgp: [ *bee, *ltlr ]
  - pgp: *ltlr # -> used for encryption if no other rule applies
